"""empty message

Revision ID: 4694311b3f44
Revises: None
Create Date: 2014-04-12 13:52:00.893458

"""

# revision identifiers, used by Alembic.
revision = '4694311b3f44'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('dimension', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('secret_access_key', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pincode_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pincode', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=256), nullable=True),
    sa.Column('state', sa.String(length=256), nullable=True),
    sa.Column('bluedart_prepaid', sa.Boolean(), nullable=True),
    sa.Column('dotzot_prepaid', sa.Boolean(), nullable=True),
    sa.Column('professional', sa.Boolean(), nullable=True),
    sa.Column('bluedart_zone', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pincode')
    )
    op.create_table('template_price_slabs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('template_id', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id', 'template_id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('design_file', sa.String(length=100), nullable=False),
    sa.Column('design_status', sa.String(length=50), nullable=False),
    sa.Column('translucent', sa.Boolean(), nullable=True),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('customers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('address1', sa.String(length=100), nullable=False),
    sa.Column('address2', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=35), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('customer_id', sa.String(length=35), nullable=True),
    sa.Column('package_cover_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('delivery_date', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tracking_url', sa.String(length=512), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('orders_products',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.String(length=40), nullable=False),
    sa.Column('product_id', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('template_price_slab_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['template_price_slab_id'], ['template_price_slabs.id'], ),
    sa.PrimaryKeyConstraint('id', 'order_id', 'product_id'),
    sa.UniqueConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_products')
    op.drop_table('orders')
    op.drop_table('customers')
    op.drop_table('roles_users')
    op.drop_table('products')
    op.drop_table('template_price_slabs')
    op.drop_table('pincode_details')
    op.drop_table('roles')
    op.drop_table('users')
    op.drop_table('subscribers')
    op.drop_table('templates')
    ### end Alembic commands ###
